# yaml-language-server: $schema=https://render.com/schema/render.yaml.json

services:
  - type: web
    name: armenian-rent-estimator-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    autoDeployTrigger: commit